# Generated by Django 4.1.6 on 2023-05-27 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inteproveapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='investor',
            name='aa',
            field=models.CharField(default='none', max_length=50),
        ),
        migrations.AddField(
            model_name='investor',
            name='actuary',
            field=models.CharField(default='none', max_length=50),
        ),
        migrations.AddField(
            model_name='investor',
            name='auditor',
            field=models.CharField(default='none', max_length=50),
        ),
        migrations.AddField(
            model_name='investor',
            name='aum',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='investor',
            name='custodian',
            field=models.CharField(default='none', max_length=50),
        ),
        migrations.AddField(
            model_name='investor',
            name='email',
            field=models.CharField(default='none', max_length=50),
        ),
        migrations.AddField(
            model_name='investor',
            name='leadconsultant',
            field=models.CharField(default='none', max_length=50),
        ),
        migrations.AddField(
            model_name='investor',
            name='mcontact',
            field=models.CharField(default='none', max_length=50),
        ),
    ]
