# Generated by Django 4.1.6 on 2023-05-27 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inteproveapp', '0002_investor_aa_investor_actuary_investor_auditor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Updates',
            fields=[
                ('updateid', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=255)),
                ('notes', models.TextField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='investor',
            name='aa',
            field=models.TextField(default='none', max_length=50),
        ),
    ]
