# Generated by Django 4.1.6 on 2023-06-03 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inteproveapp', '0004_updates_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supervisor',
            name='user_ptr',
        ),
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(max_length=1),
        ),
        migrations.DeleteModel(
            name='Researcher',
        ),
        migrations.DeleteModel(
            name='Supervisor',
        ),
    ]
